-- Mood Tracker Tablosu
CREATE TABLE IF NOT EXISTS mood_tracker (
    id bigint generated by default as identity primary key,
    user_role text not null, -- 'rabbit' veya 'fox'
    mood_type text not null, -- 'happy', 'sad', 'tired', 'love', 'angry', 'excited'
    note text, -- opsiyonel not
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) Politikaları
ALTER TABLE mood_tracker ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON mood_tracker FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON mood_tracker FOR INSERT WITH CHECK (true);
